import path from "node:path";

import type {
  AspectRatio,
  Background,
  ImageModelConfig,
  OutputFormat,
  Quality,
  ResolvedImageOptions,
} from "../types/index.js";
import { PipelineError } from "./errors.js";

export const SIZE_BY_RATIO: Record<AspectRatio, string> = {
  "1:1": "1024x1024",
  "16:10": "1536x960",
  "3:2": "1536x1024",
  "16:9": "1536x864",
  "4:5": "1024x1280",
  "2:3": "1024x1536",
  "9:16": "864x1536",
};

const EXTENSION_FORMAT: Record<string, OutputFormat> = {
  ".jpeg": "jpeg",
  ".jpg": "jpeg",
  ".png": "png",
  ".webp": "webp",
};

export function validateSize(size: string): string {
  if (size === "auto") return size;
  const match = /^(\d{2,4})x(\d{2,4})$/.exec(size);
  if (!match) {
    throw new PipelineError("INVALID_INPUT", "size must use WIDTHxHEIGHT, for example 1536x960.");
  }

  const width = Number(match[1]);
  const height = Number(match[2]);
  const ratio = width / height;

  if (width % 16 !== 0 || height % 16 !== 0) {
    throw new PipelineError("INVALID_INPUT", "Image width and height must be divisible by 16.");
  }
  if (ratio < 1 / 3 || ratio > 3) {
    throw new PipelineError("INVALID_INPUT", "Image aspect ratio must be between 1:3 and 3:1.");
  }
  if (width > 3840 || height > 3840 || width * height > 3840 * 2160) {
    throw new PipelineError("INVALID_INPUT", "Image size exceeds the supported GPT Image 2 bounds.");
  }

  return `${width}x${height}`;
}

export function formatFromOutputPath(outputPath: string): OutputFormat {
  const extension = path.extname(outputPath).toLowerCase();
  const format = EXTENSION_FORMAT[extension];
  if (!format) {
    throw new PipelineError(
      "INVALID_INPUT",
      "output_path must end in .png, .jpg, .jpeg, or .webp. SVG output is not generated by this raster pipeline.",
    );
  }
  return format;
}

export function resolveImageOptions(args: {
  aspectRatio?: AspectRatio;
  background: Background;
  config: ImageModelConfig;
  outputCompression: number;
  outputFormat?: OutputFormat;
  outputPath: string;
  quality: Quality;
  size?: string;
}): ResolvedImageOptions {
  const pathFormat = formatFromOutputPath(args.outputPath);
  const format = args.outputFormat ?? pathFormat;
  if (format !== pathFormat) {
    throw new PipelineError(
      "INVALID_INPUT",
      `output_format '${format}' conflicts with the '${path.extname(args.outputPath)}' output extension.`,
    );
  }

  const size = validateSize(args.size ?? (args.aspectRatio ? SIZE_BY_RATIO[args.aspectRatio] : "1024x1024"));
  validateBackground(args.background, format, args.config.model);

  return {
    background: args.background,
    format,
    quality: args.quality,
    size,
    ...(format === "jpeg" || format === "webp" ? { compression: args.outputCompression } : {}),
  };
}

export function validateBackground(
  background: Background,
  format: OutputFormat,
  model: string,
): void {
  if (background === "transparent" && model.startsWith("gpt-image-2")) {
    throw new PipelineError(
      "INVALID_INPUT",
      `${model} does not support transparent backgrounds. Use 'opaque' or 'auto'.`,
    );
  }
  if (background === "transparent" && format === "jpeg") {
    throw new PipelineError("INVALID_INPUT", "JPEG cannot preserve a transparent background.");
  }
}

export function parseDimension(size: string): { height: number; width: number } {
  if (size === "auto") {
    throw new PipelineError("INVALID_INPUT", "Automatic size does not have fixed dimensions.");
  }
  const [widthRaw, heightRaw] = size.split("x");
  return { height: Number(heightRaw), width: Number(widthRaw) };
}
